tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

# Binaries
brew "bash"
brew "zsh"
brew "gh"
brew "awscli"
brew "aws-cdk"
brew "coreutils"
brew "ffmpeg"
brew "git"
brew "grep"
brew "httpie"
brew "mackup"
brew "mas"
brew "trash"

# Development
brew "diff-so-fancy"
brew "go"
brew "node"
brew "php"
brew "composer"
brew "podman"
brew "python"
brew "redis"
brew "rbenv"
brew "ruby"
brew "sqlite"
brew "yarn"
brew "kubernetes-cli"
brew "typescript"
brew "hyperkit"
brew "k3d"

# Apps
cask "temurin"
cask "firefox"
cask "google-chrome"
cask "google-drive"
cask "visual-studio-code"
cask "vlc"
cask "iterm2"
cask "authy"
cask "surfshark"
cask "istat-menus"
cask "microsoft-office"
cask "paragon-ntfs"
cask "postman"
cask "beekeeper-studio"
cask "balenaetcher"
cask "docker"
cask "vivaldi"
cask "fork"

# Fonts
cask "font-fira-code"
cask "font-menlo-for-powerline"
cask "font-lato"
cask "font-meslo-lg-nerd-font"

# Mac App Store
mas "Moom", id: 419330170
